template: |
  ### Summary
  
  - insert summary here
  
  ### Contributions
  
  $CHANGES

  [Full Changelog](https://github.com/saferill/MySender/commits/main)

  Windows binaries are signed according to the [Code signing policy](https://github.com/saferill/MySender/blob/main/CODE_SIGNING.md).
