blank_issues_enabled: false
contact_links:
  - name: Get latest MySender
    url: https://github.com/saferill/MySender/releases/latest
    about: Your issue may be version related, so try updating first

  - name: GitHub Discussions
    url: https://github.com/saferill/MySender/discussions
    about: Discuss feature ideas or questions here
    
