display_name: MySender
package_name: mysender
version: null
maintainer:
  name: Tienisto
  email: dev.tien.donam@gmail.com
license: Apache-2.0
url: https://github.com/saferill/MySender
icon: assets/img/logo-512.png
desktop:
  Name: MySender
  GenericName: An open-source cross-platform alternative to AirDrop
  Comment: An open-source cross-platform alternative to AirDrop
  Categories: Network;Utility;
  Terminal: false
  StartupNotify: false
  Keywords: file;sharing;airdrop;transfer;share;cross-platform;
summary: Share files easily with MySender
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
