name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish MySender
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: MySender.MySender
          installers-regex: 'MySender-(?!CLI-).*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
      - name: Publish MySender CLI
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: MySender.MySender.CLI
          installers-regex: 'MySender-CLI-.*\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
